cBlog/urls.py
from blog_app import views
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='home/', permanent=False), name='index'),
    path('conta/', include('django.contrib.auth.urls')),
    path('cadastro/', views.UserCreationView.as_view(), name='cadastro'),
    path('cadastro/sucesso/', views.UserCreationSucessView.as_view(), name='cadastro_sucesso'),
    path('home/', views.HomePageView.as_view(), name='home'),
    path('publicar/', views.PostCreationView.as_view(), name='publicar'),
    path('<str:username>/', views.UserPostsView.as_view(), name='perfil_usuario'),
    path('<str:username>/<int:pk>/', views.ComentarioCreationView.as_view(), name='post_detalhes'),
] 

blog_app/models.py
from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import truncatechars


class Post(models.Model):
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    conteudo = models.TextField(max_length=200, blank=False, null=False)
    criado_em = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-criado_em"]

    @property
    def descricao_curta(self):
        return truncatechars(self.conteudo, 60)

    def __str__(self):
        return self.descricao_curta

    def get_comentarios(self):
        comentarios = Comentario.objects.filter(post_id=self.pk)
        return comentarios


class Comentario(models.Model):
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    conteudo = models.CharField(max_length=200, blank=False, null=False)
    criado_em = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["criado_em"]

    def __str__(self):
        return self.conteudo

    @property
    def descricao_curta(self):
        return truncatechars(self.conteudo, 60)


class Seguir(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    seguindo = models.ManyToManyField(User, related_name="seguindo", blank=True)

    class Meta:
        verbose_name = "Seguir"
        verbose_name_plural = "Seguir"

    def __str__(self):
        seguindo = ", ".join(str(i) for i in self.seguindo.all())
        return "{}".format(seguindo)

blog_app/forms.py
from blog_app.models import Comentario, Post
from django import forms
from django.contrib.auth import forms as auth_forms
from django.contrib.auth.models import User

from .models import Seguir


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ["autor"]


class ComentarioForm(forms.ModelForm):
    class Meta:
        model = Comentario
        exclude = ["autor", "post"]


class SeguirForm(forms.ModelForm):
    class Meta:
        model = Seguir
        exclude = ["user", "seguindo"]


class UserCreationForm(auth_forms.UserCreationForm):
    class Meta(auth_forms.UserCreationForm.Meta):
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self._meta.model.USERNAME_FIELD in self.fields:
            self.fields[self._meta.model.USERNAME_FIELD].widget.attrs[
                "autofocus"
            ] = False
        self.fields["first_name"].widget.attrs["required"] = True
        self.fields["last_name"].widget.attrs["required"] = True

blog_app/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.urls import reverse
from django.views.generic import ListView, TemplateView
from django.views.generic.edit import FormView

from .forms import ComentarioForm, PostForm, SeguirForm, UserCreationForm
from .models import Comentario, Post, Seguir


class HomePageView(LoginRequiredMixin, ListView):
    model = Post
    login_url = "login"
    template_name = "blog_app/home.html"
    paginate_by = 30

    def get_queryset(self):
        seguindo = Seguir.objects.filter(user=self.request.user).values("seguindo")
        tupla_seguindo_id = []
        for i in seguindo:
            tupla_seguindo_id.append(i["seguindo"])
        return Post.objects.filter(autor__in=tupla_seguindo_id)


class UserCreationView(FormView):
    template_name = "registration/cadastro.html"
    form_class = UserCreationForm

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("cadastro_sucesso")


class UserCreationSucessView(TemplateView):
    template_name = "registration/cadastroSucesso.html"


class PostCreationView(LoginRequiredMixin, FormView):
    login_url = "login"
    template_name = "blog_app/publicarPost.html"
    form_class = PostForm

    def form_valid(self, form):
        form = form.save(commit=False)
        form.autor = self.request.user
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse(
            "perfil_usuario",
            kwargs={"username": self.request.user.get_username()},
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form_old"] = self.request.POST
        return context


class UserPostsView(ListView, FormView):
    model = Post
    form_class = SeguirForm
    template_name = "blog_app/perfilusuario.html"
    paginate_by = 30

    def form_valid(self, form):
        form = form.save(commit=False)
        form.user = self.request.user
        queryset_perfil = User.objects.get(username=self.kwargs["username"])
        form.save()
        form.seguindo.add(queryset_perfil)
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            context["usuario"] = User.objects.get(username=self.kwargs["username"])
            segue = False
            seguindo = Seguir.objects.filter(user=self.request.user)
            seguindo_string = seguindo.__str__()
            perfil = User.objects.get(username=self.kwargs["username"])
            username = perfil.get_username()
            if username in seguindo_string:
                segue = True
            context["segue"] = segue
        except:
            pass
        return context

    def get_queryset(self):
        return Post.objects.filter(autor__username=self.kwargs["username"])

    def get_success_url(self):
        return reverse(
            "perfil_usuario",
            kwargs={"username": self.kwargs["username"]},
        )


class ComentarioCreationView(LoginRequiredMixin, FormView, ListView):
    login_url = "login"
    template_name = "blog_app/postDetalhes.html"
    form_class = ComentarioForm
    Model = Comentario
    paginate_by = 30

    def form_valid(self, form):
        form = form.save(commit=False)
        form.autor = self.request.user
        form.post = Post.objects.get(pk=self.kwargs["pk"])
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse(
            "post_detalhes",
            kwargs={"pk": self.kwargs["pk"], "username": self.kwargs["username"]},
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post"] = Post.objects.get(pk=self.kwargs["pk"])
        return context

    def get_queryset(self):
        return Comentario.objects.filter(post__pk=self.kwargs["pk"])

blog_app/templates/blog_app/baseLogado.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block titulo %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    {% load static %}
</head>

<body style="position:relative; min-height: 100vh; padding-bottom: 5%; ">

    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-0 border-bottom">
        <p class="d-flex align-items-center col-md-3 mb-2 mb-md-0">
          <img class="img-fluid col-md-3 ms-md-auto" src="{% static 'blog_app/logo_icon.svg' %}"></img>
        </p>
  
        <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
          <li><a href="{% url 'home' %}" class="nav-link px-2 link-dark">Inicio</a></li>
          {% if user.is_authenticated %}
            <li><a href="{% url 'perfil_usuario' user.get_username %}" class="nav-link px-2 link-dark">Perfil</a></li>
          {% endif %}
        </ul>
  
        <div class="col-md-3 ms-md-auto">
          {% if user.is_authenticated %}
            <a href="{% url 'publicar' %}" class="text-decoration-none"><button type="button" class="btn btn-outline-dark">Publicar</button></a>
            <a href="{% url 'logout' %}" class="text-decoration-none"><button type="button" class="btn btn-outline-dark">Sair</button></a>
          {% else %}
            <a href="{% url 'login' %}" class="text-decoration-none"><button type="button" class="btn btn-outline-dark">Entrar</button></a>
          {% endif %}
        </div>
    </header>
      
      <main class="container">
        <div class="col-md-8 offset-md-2" style=" border-left: 0.2px solid rgba(0, 0, 0, 0.2) ; border-right: 0.2px solid rgba(0, 0, 0, 0.2) ;">
        {% block main %}{% endblock %}
        </div>
      </main>
    <br>
      

    <footer style="position:absolute; bottom: 0; width: 100%;" >
      <hr>
      <p class="text-center text-muted">© 2022 cBlog, Inc</p>
    </footer>

</body>

</html>

blog_app/templates/blog_app/home.html
{% extends "blog_app/baseLogado.html" %}
{% block titulo %}Minhas Publicações{% endblock %}

{% block main %}
<div class="collapse" id="collapseExample">
  <form action="{% url 'Publicar post' %}" method="post">
    {% csrf_token %}

    <div class="mb-3">
      <label for="id_conteudo" class="form-label"></label>
      <textarea maxlength="200" class="form-control" id="id_conteudo" name="conteudo" rows="4"></textarea>
    </div>
  
    <p style="text-align:right;">
      <button class="btn btn-secondary shadow-none btn-sm"  type="submit" style="margin-right:6%;">
      Publicar
      </button>
    </p>
  </form>
</div>
<h3 class=" mb-3 fst-italic">
  Minhas publicações
  <button class="btn btn-secondary shadow-none btn-sm" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample" style="float: right;margin-right:6%;">
    Novo Post
  </button>
</h3>
<hr>
{% if meusposts %}
{% for post in meusposts %}
<article class="blog-post">
  <p>{{ post.conteudo }}</p>
  <p class="blog-post-meta"><small>{{ post.criado_em }}</small></p>
  <hr>
</article>
{% endfor %}
{% endif %}
{% if not meusposts %}
<article class="blog-post">
  <h6>Você não publicou nenhum post ainda.</h6>
</article>
{% endif %}
{% endblock %}

blog_app/templates/blog_app/perfilUsuario.html
{% extends "blog_app/baseLogado.html" %}
{% block titulo %}{{ usuario.get_full_name }} / @{{ usuario.get_username }}{% endblock %}

{% block main %}

<h3 class="mb-2 pt-3 fst-italic" style="margin-left:2%; display: inline-block;">
  {{ usuario.get_full_name }}
</h3>

{% if usuario.get_username != user.get_username and user.is_authenticated %}
  {% if not segue %}
    <form method="post" style="float: right; margin-right: 1%;" class="text-decoration-none mb-2 pt-3">
      {% csrf_token %}
      <button type="submit" class="btn btn-outline-dark ">Seguir</button>
    </form>
  {% else %}
    <p style="float: right; margin-right: 1%;" class="text-decoration-none mb-2 pt-3">
      <button class=" btn btn-outline-dark " disabled>Seguindo</button>
    </p>
  {% endif %}
{% endif %}

<hr style="margin-bottom: 8px; ">

{% if object_list %}

  {% for post in object_list %}
    <a href="{% url 'post_detalhes' username=usuario.get_username pk=post.pk %}" style="text-decoration: none; color: black;">
      <article class="blog-post">
        <p class="blog-post-meta" style="display:inline-block; margin-left: 1%; margin-bottom: 1%;">@<strong>{{ post.autor.get_username }}</strong></p>
        <p class="blog-post-meta pt-1" style="float: right; font-size:smaller; margin-bottom: 1%; margin-right: 1%;">· <small>{{ post.criado_em }}</small></p>
        <p style="margin-left:4%; margin-right: 4%; padding-bottom: 1%; opacity: 0.87;">{{ post.conteudo }}</p>
      </article>
    </a>
    <hr style="margin-bottom: 8px; margin-bottom: 8px;">
  {% endfor %}

  {% if page_obj.paginator.num_pages > 1 %}
    <div class="pagination d-flex justify-content-center">
      <span class="step-links">
          {% if page_obj.has_previous %}
              <a style="color: black;font-size:smaller;" href="?page=1">&laquo; primeira</a>
              <a style="color: black;font-size:smaller;" href="?page={{ page_obj.previous_page_number }}">anterior</a>
          {% endif %}

          <span class="current">
              Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
          </span>

          {% if page_obj.has_next %}
              <a style="color: black;font-size:smaller;" href="?page={{ page_obj.next_page_number }}">próxima</a>
              <a style="color: black;font-size:smaller;" href="?page={{ page_obj.paginator.num_pages }}">última &raquo;</a>
          {% endif %}
      </span>
    </div>
    <hr style="margin-bottom: 8px; margin-bottom: 8px;">
  {% endif %}
  
{% else %}
  <article class="blog-post">
    <h6 style="margin-left: 1%;">Este Usuário não publicou nenhum post ainda.</h6>
  </article>
  <hr style="margin-bottom: 8px; margin-bottom: 8px;">
{% endif %}

{% endblock %}

blog_app/templates/blog_app/postDetalhes.html
{% extends "blog_app/baseLogado.html" %}
{% block titulo %}Post de {{ post.autor.get_full_name }} {% endblock %}

{% block main %}

<article class="blog-post pt-3">

  <a href="{% url 'perfil_usuario' post.autor.get_username %}" style="text-decoration: none; color: black;">
    <p class="blog-post-meta" style="display:inline-block; margin-left: 1%; margin-bottom: 1%;">@<strong>{{ post.autor.get_username }}</strong></p>
  </a>
  <p class="blog-post-meta pt-1" style="display: inline-block; margin-bottom: 1%; margin-right: 1%;">· {{ post.autor.get_full_name }}</p>
  <p class="blog-post-meta" style="float: right; font-size:smaller; margin-bottom: 1%; margin-right: 1%;">· <small>{{ post.criado_em }}</small></p>
  <p style="margin-left:4%; margin-right: 4%; padding-bottom: 1%; opacity: 0.87;">{{ post.conteudo }}</p>
  <hr style="margin-bottom: 8px; margin-bottom: 8px;">

  {% if object_list %}
    <p style="margin-left: 1%;"><small>Comentarios 💬</small></p>
    <div style="margin-left: 6%; border-left: 0.2px solid rgba(0, 0, 0, 0.2) ;">

      {% for comentario in object_list %}
        <a href="{% url 'perfil_usuario' comentario.autor.get_username %}" style="text-decoration: none; color: black;">
          <p class="blog-post-meta" style="display:inline-block; margin-left: 1%; margin-bottom: 1%;">@<strong>{{ comentario.autor.get_username }}</strong></p>
        </a>
        <p class="blog-post-meta pt-1" style="display: inline-block; margin-bottom: 1%; margin-right: 1%;">· {{ comentario.autor.get_full_name }}</p>
        <p class="blog-post-meta" style="float: right; font-size:smaller; margin-bottom: 1%; margin-right: 1%;">· <small>{{ comentario.criado_em }}</small></p>
        <p style="margin-left:4%; margin-right: 4%; padding-bottom: 1%; opacity: 0.87;">{{ comentario.conteudo }}</p>
        <hr style="margin-bottom: 8px; margin-bottom: 8px;">
      {% endfor %}
      
    </div>

  {% else %}

    <p style="margin-left: 1%;"><small>Seja o primeiro a comentar 👇</small></p>

  {% endif %}
  
  <div style="margin: 1%;">
    <form method="post">
      {% csrf_token %}
      {{ form.conteudo.errors }}
      <div class="mb-3">
        <label for="id_conteudo" class="form-label"></label>
        <textarea class="form-control" id="id_conteudo" name="conteudo" placeholder="Comente aqui!" required>{{ form_old.conteudo }}</textarea>
      </div>
      <p style="text-align:right;">
        <button class="btn btn-secondary shadow-none btn-sm"  type="submit" style="margin-right:6%;">
        Comentar
        </button>
      </p>
    </form>
  </div>

  {% if page_obj.paginator.num_pages > 1 %}
    <div class="pagination d-flex justify-content-center">
      <span class="step-links">
          {% if page_obj.has_previous %}
              <a style="color: black;font-size:smaller;" href="?page=1">&laquo; primeira</a>
              <a style="color: black;font-size:smaller;" href="?page={{ page_obj.previous_page_number }}">anterior</a>
          {% endif %}

          <span class="current">
              Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
          </span>

          {% if page_obj.has_next %}
              <a style="color: black;font-size:smaller;" href="?page={{ page_obj.next_page_number }}">próxima</a>
              <a style="color: black;font-size:smaller;" href="?page={{ page_obj.paginator.num_pages }}">última &raquo;</a>
          {% endif %}
      </span>
    </div>
  {% endif %}

</article>
<hr style="margin-bottom: 8px; margin-bottom: 8px;">
{% endblock %}

blog_app/templates/blog_app/pubPerfil.html
{% extends "blog_app/baseLogado.html" %}
{% block titulo %}Minhas Publicações{% endblock %}

{% block main %}
<h3 class="pb-4 mb-4 fst-italic border-bottom">
  Publicações de {nome do Usuário}
</h3>

<article class="blog-post">
  <p>This blog post shows a few different types of content that’s supported and styled with Bootstrap. Basic typography, lists, tables, images, code, and more are all supported as expected.</p>
  <p class="blog-post-meta"><small>{data} por <a href="#">{autor}</a></small></p>
  <p>
    <button class="btn btn-secondary shadow-none btn-sm" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
      Comentar
    </button>
  </p>
  <div class="collapse" id="collapseExample">
    <div class="card card-body">
      form
    </div>
  </div>
  <hr>
</article>
{% endblock %}

blog_app/templates/blog_app/publicarPost.html
{% extends "blog_app/baseLogado.html" %}
{% block titulo %}Novo Post{% endblock %}

{% block main %}

<h3 class="pt-3 fst-italic" style="margin-left:2%;">
  Novo post
</h3>

<div style="margin: 1%;">
  <form method="post">
    {% csrf_token %}
    {{ form.conteudo.errors }}
    <div class="mb-3">
      <label for="id_conteudo" class="form-label"></label>
      <textarea class="form-control" id="id_conteudo" name="conteudo" rows="4" placeholder="O que você está pensando?">{{ form_old.conteudo }}</textarea>
    </div>
    <p style="text-align:right;">
      <button class="btn btn-secondary shadow-none btn-sm"  type="submit" style="margin-right:6%;">
      Publicar
      </button>
    </p>
  </form>
</div>
<hr>

{% endblock %}